# keycloak + postges
version: "3"
name: "keycloak"
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "./postgresql_data_keycloak:/bitnami/postgresql"

  keycloak:
    image: docker.io/bitnami/keycloak:19.0.3
    depends_on:
      - postgresql
    ports:
      - "80:8080"
volumes:
  postgresql_data_keycloak:
    driver: local
