# Mysql + Phpmyadmin
version: "3"
name: "mysql-db"
networks:
  app-mysql-db:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-mysql-db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - app-mysql-db
