# Postgre + Adminer
version: "3"
name: "postgres-db"
networks:
  app-postgres-db:
    driver: bridge
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-data:/var/lib/postgres
    ports:
      - 5432:5432
    networks:
      - app-postgres-db
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - app-postgres-db
